// <auto-generated />
using System;
using EMS_Web_Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS_Web_Application.Migrations
{
    [DbContext(typeof(EMSDBContext))]
    partial class EMSDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EMS_Web_Application.Models.DepartmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Department = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Department = "CSR"
                        });
                });

            modelBuilder.Entity("EMS_Web_Application.Models.EmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("ntext")
                        .HasColumnName("Full_Name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DOB = new DateTime(2023, 3, 20, 21, 33, 17, 516, DateTimeKind.Local).AddTicks(7556),
                            Department = "IT",
                            DepartmentId = 1,
                            Email = "alvin@gmail.com",
                            Name = "Alvin Root",
                            Phone = "099232312"
                        },
                        new
                        {
                            Id = 2,
                            DOB = new DateTime(2023, 3, 21, 21, 33, 17, 516, DateTimeKind.Local).AddTicks(7575),
                            Department = "HR",
                            DepartmentId = 2,
                            Email = "trish@gmail.com",
                            Name = "Tricia Tagle",
                            Phone = "099232322312"
                        },
                        new
                        {
                            Id = 3,
                            DOB = new DateTime(2023, 3, 22, 21, 33, 17, 516, DateTimeKind.Local).AddTicks(7577),
                            Department = "CSR",
                            DepartmentId = 3,
                            Email = "Joan@gmail.com",
                            Name = "Joan DC",
                            Phone = "09319232312"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
